#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidSlideLayout.Resource", IsApplication=false)]

namespace AndroidSlideLayout
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public static int draggable_all_direction = 2130771974;
			
			// aapt resource value: 0x7f010001
			public static int draggable_bottom_direction = 2130771969;
			
			// aapt resource value: 0x7f010005
			public static int draggable_horizontal_direction = 2130771973;
			
			// aapt resource value: 0x7f010003
			public static int draggable_left_direction = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int draggable_right_direction = 2130771972;
			
			// aapt resource value: 0x7f010000
			public static int draggable_top_direction = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int draggable_vertical_direction = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020001
			public static int ApplicationName = 2130837505;
			
			// aapt resource value: 0x7f020000
			public static int Hello = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SlideLayout = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 6
			public static int SlideLayout_draggable_all_direction = 6;
			
			// aapt resource value: 1
			public static int SlideLayout_draggable_bottom_direction = 1;
			
			// aapt resource value: 5
			public static int SlideLayout_draggable_horizontal_direction = 5;
			
			// aapt resource value: 3
			public static int SlideLayout_draggable_left_direction = 3;
			
			// aapt resource value: 4
			public static int SlideLayout_draggable_right_direction = 4;
			
			// aapt resource value: 0
			public static int SlideLayout_draggable_top_direction = 0;
			
			// aapt resource value: 2
			public static int SlideLayout_draggable_vertical_direction = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
